### ISSUE TITLE
Build Error: Sensor.h not found

### ISSUE THREAD

**Issue by hayatuabdul** [donank/smart-bottle#3]
In file included from /home/pi/smart-bottle/main/main.cpp:4:
/home/pi/smart-bottle/main/ph/ph.h:9:10: fatal error: sensor.h: No such file or directory
    9 | #include "sensor.h"
      |          ^~~~
compilation terminated.
make[2]: * [CMakeFiles/main.dir/build.make:82: CMakeFiles/main.dir/main.cpp.o] Error 1
make[1]: * [CMakeFiles/Makefile2:212: CMakeFiles/main.dir/all] Error 2
make: * [Makefile:149: all] Error 2

**Comment by donank** [comment]
It was an issue with incorrect implementation of `add_subdirectory()` in cmake parent directory. Should be fixed now.
